/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.awt.PopupMenu;
import java.util.Calendar;
import javax.swing.JFrame;

/**
 *
 * @author Igor
 */
public class AquaparkyGui extends javax.swing.JFrame {

    /**
     * Creates new form AquaparkyGui
     */
    public AquaparkyGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        showHidePanel1 = new javax.swing.JPanel();
        BtnPrehlad1 = new javax.swing.JButton();
        btnNavstevnost1 = new javax.swing.JButton();
        btnAtrakcie1 = new javax.swing.JButton();
        btnStatistika1 = new javax.swing.JButton();
        panelAll2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        showHidePanel = new javax.swing.JPanel();
        BtnPrehlad = new javax.swing.JButton();
        btnNavstevnost = new javax.swing.JButton();
        btnAtrakcie = new javax.swing.JButton();
        btnStatistika = new javax.swing.JButton();
        panelAll = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        showHidePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                showHidePanel1ComponentHidden(evt);
            }
        });

        BtnPrehlad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/rozdelit_pracu.png"))); // NOI18N
        BtnPrehlad1.setText("<html>Rezervacia procedur</html>");
        BtnPrehlad1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPrehlad1.setInheritsPopupMenu(true);
        BtnPrehlad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrehlad1MouseClicked(evt);
            }
        });

        btnNavstevnost1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/predajne_zanzami.png"))); // NOI18N
        btnNavstevnost1.setText("<html>Kupa listka do aquaparku</html>");
        btnNavstevnost1.setActionCommand("");
        btnNavstevnost1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavstevnost1.setInheritsPopupMenu(true);
        btnNavstevnost1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNavstevnost1MouseClicked(evt);
            }
        });

        btnAtrakcie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/spravovat_nastroje.png"))); // NOI18N
        btnAtrakcie1.setText("<html>Sprava cien</html>");
        btnAtrakcie1.setActionCommand("");
        btnAtrakcie1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtrakcie1.setInheritsPopupMenu(true);
        btnAtrakcie1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrakcie1MouseClicked(evt);
            }
        });

        btnStatistika1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/upravit_konto.png"))); // NOI18N
        btnStatistika1.setText("<html>Generovanie udalosti</html>");
        btnStatistika1.setActionCommand("");
        btnStatistika1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStatistika1.setInheritsPopupMenu(true);
        btnStatistika1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatistika1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showHidePanel1Layout = new javax.swing.GroupLayout(showHidePanel1);
        showHidePanel1.setLayout(showHidePanel1Layout);
        showHidePanel1Layout.setHorizontalGroup(
            showHidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showHidePanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BtnPrehlad1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavstevnost1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnAtrakcie1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnStatistika1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showHidePanel1Layout.setVerticalGroup(
            showHidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showHidePanel1Layout.createSequentialGroup()
                .addGroup(showHidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPrehlad1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavstevnost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistika1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtrakcie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAll2Layout = new javax.swing.GroupLayout(panelAll2);
        panelAll2.setLayout(panelAll2Layout);
        panelAll2Layout.setHorizontalGroup(
            panelAll2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAll2Layout.setVerticalGroup(
            panelAll2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(showHidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAll2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showHidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelAll2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vstupenky", jPanel2);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        showHidePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                showHidePanelComponentHidden(evt);
            }
        });

        BtnPrehlad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/home120.png"))); // NOI18N
        BtnPrehlad.setText("<html>Prehľadom vyťaženosti jednotlivých aquaparkov</html>");
        BtnPrehlad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPrehlad.setInheritsPopupMenu(true);
        BtnPrehlad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrehladMouseClicked(evt);
            }
        });

        btnNavstevnost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/predajne_zanzami.png"))); // NOI18N
        btnNavstevnost.setText("<html>Návštevnosť a tržby Aquaparkov</html>");
        btnNavstevnost.setActionCommand("");
        btnNavstevnost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavstevnost.setInheritsPopupMenu(true);
        btnNavstevnost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNavstevnostMouseClicked(evt);
            }
        });

        btnAtrakcie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/auto.png"))); // NOI18N
        btnAtrakcie.setText("<html> Atrakcie</html>");
        btnAtrakcie.setActionCommand("");
        btnAtrakcie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtrakcie.setInheritsPopupMenu(true);
        btnAtrakcie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrakcieMouseClicked(evt);
            }
        });

        btnStatistika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/zobrazit_statistiky_1.png"))); // NOI18N
        btnStatistika.setText("<html> Statistiku príjmov a  počtu návštevníkov</html>");
        btnStatistika.setActionCommand("");
        btnStatistika.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStatistika.setInheritsPopupMenu(true);
        btnStatistika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatistikaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showHidePanelLayout = new javax.swing.GroupLayout(showHidePanel);
        showHidePanel.setLayout(showHidePanelLayout);
        showHidePanelLayout.setHorizontalGroup(
            showHidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showHidePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BtnPrehlad, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNavstevnost, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnAtrakcie, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showHidePanelLayout.setVerticalGroup(
            showHidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showHidePanelLayout.createSequentialGroup()
                .addGroup(showHidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPrehlad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavstevnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtrakcie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAllLayout = new javax.swing.GroupLayout(panelAll);
        panelAll.setLayout(panelAllLayout);
        panelAllLayout.setHorizontalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAllLayout.setVerticalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(showHidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showHidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Výpis aquaparkov", jPanel1);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setText("Informačný systém pre Aquaparky ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatistikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikaMouseClicked
//        showHidePanel.setVisible(false);
        panelAll.removeAll();
        panelAll.repaint();
        panelAll.invalidate();
        panelAll.validate();
        PrehladVyPanel prehladVyPanel = new PrehladVyPanel();
        prehladVyPanel.setBounds(1, 1, panelAll.getWidth(), panelAll.getHeight());
        panelAll.add(prehladVyPanel);
        prehladVyPanel.setVisible(true);
        panelAll.invalidate();
        panelAll.validate();
       
         Calendar.getInstance();

    }//GEN-LAST:event_btnStatistikaMouseClicked

    private void showHidePanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_showHidePanelComponentHidden

    }//GEN-LAST:event_showHidePanelComponentHidden

    private void btnAtrakcieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrakcieMouseClicked
        panelAll.removeAll();
        panelAll.invalidate();
        panelAll.validate();
        panelAll.repaint();
        Atrakcie atrakciePanel = new Atrakcie();
        atrakciePanel.setBounds(1, 1, panelAll.getWidth(), panelAll.getHeight());
        panelAll.add(atrakciePanel);
        atrakciePanel.setVisible(true);
        panelAll.invalidate();
        panelAll.validate();
    }//GEN-LAST:event_btnAtrakcieMouseClicked

    private void btnNavstevnostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNavstevnostMouseClicked
        panelAll.removeAll();
        panelAll.invalidate();
        panelAll.validate();
        panelAll.repaint();
        NavstevnostAVyt navstevnostPanel = new NavstevnostAVyt();
        navstevnostPanel.setBounds(1, 1, panelAll.getWidth(), panelAll.getHeight());
        panelAll.add(navstevnostPanel);
        navstevnostPanel.setVisible(true);
        panelAll.invalidate();
        panelAll.validate();
    }//GEN-LAST:event_btnNavstevnostMouseClicked

    private void BtnPrehladMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrehladMouseClicked
        panelAll.removeAll();
        panelAll.invalidate();
        panelAll.validate();
        panelAll.repaint();
        VytazenostGui vytazenostPanel = new VytazenostGui();
        vytazenostPanel.setBounds(1, 1, panelAll.getWidth(), panelAll.getHeight());
        panelAll.add(vytazenostPanel);
        vytazenostPanel.setVisible(true);
        panelAll.invalidate();
        panelAll.validate();

    }//GEN-LAST:event_BtnPrehladMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void BtnPrehlad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrehlad1MouseClicked
       panelAll2.removeAll();
        panelAll2.invalidate();
        panelAll2.validate();
        panelAll2.repaint();
        RezervaciaProcedur okno = new RezervaciaProcedur();
        okno.setBounds(1, 1, panelAll2.getWidth(), panelAll2.getHeight());
        panelAll2.add(okno);
        okno.setVisible(true);
        panelAll2.invalidate();
        panelAll2.validate();
    }//GEN-LAST:event_BtnPrehlad1MouseClicked

    private void btnNavstevnost1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNavstevnost1MouseClicked
       panelAll2.removeAll();
        panelAll2.invalidate();
        panelAll2.validate();
        panelAll2.repaint();
        KupaListka okno = new KupaListka();
        okno.setBounds(1, 1, panelAll2.getWidth(), panelAll2.getHeight());
        panelAll2.add(okno);
        okno.setVisible(true);
        panelAll2.invalidate();
        panelAll2.validate();
    }//GEN-LAST:event_btnNavstevnost1MouseClicked

    private void btnAtrakcie1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrakcie1MouseClicked
        panelAll2.removeAll();
        panelAll2.invalidate();
        panelAll2.validate();
        panelAll2.repaint();
        ZmenaCenyVstupneho okno = new ZmenaCenyVstupneho();
        okno.setBounds(1, 1, panelAll2.getWidth(), panelAll2.getHeight());
        panelAll2.add(okno);
        okno.setVisible(true);
        panelAll2.invalidate();
        panelAll2.validate();
    }//GEN-LAST:event_btnAtrakcie1MouseClicked

    private void btnStatistika1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistika1MouseClicked
         panelAll2.removeAll();
        panelAll2.invalidate();
        panelAll2.validate();
        panelAll2.repaint();
        
    }//GEN-LAST:event_btnStatistika1MouseClicked

    private void showHidePanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_showHidePanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_showHidePanel1ComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AquaparkyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AquaparkyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AquaparkyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AquaparkyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AquaparkyGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPrehlad;
    private javax.swing.JButton BtnPrehlad1;
    private javax.swing.JButton btnAtrakcie;
    private javax.swing.JButton btnAtrakcie1;
    private javax.swing.JButton btnNavstevnost;
    private javax.swing.JButton btnNavstevnost1;
    private javax.swing.JButton btnStatistika;
    private javax.swing.JButton btnStatistika1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAll;
    private javax.swing.JPanel panelAll2;
    private javax.swing.JPanel showHidePanel;
    private javax.swing.JPanel showHidePanel1;
    // End of variables declaration//GEN-END:variables
}
